import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import api, { API_BASE_URL } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { Sparkles, Plus, Edit, Trash2, Clock, Upload, AlertCircle, CheckCircle2, Loader, Tag, HelpCircle } from 'lucide-react';
import LoadingSpinner from '../components/LoadingSpinner';

const MyServices = () => {
  const { user } = useAuth();
  const [listings, setListings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [editItem, setEditItem] = useState(null);
  
  // API feedback status
  const [msg, setMsg] = useState({ text: '', type: '' });
  const [submitting, setSubmitting] = useState(false);
  
  // Image Upload
  const [uploadedImageUrl, setUploadedImageUrl] = useState('');
  const [uploadingImage, setUploadingImage] = useState(false);
  
  // AI Generator status
  const [briefInput, setBriefInput] = useState('');
  const [generatingAi, setGeneratingAi] = useState(false);

  const { register, handleSubmit, setValue, reset, formState: { errors } } = useForm();

  const fetchMyListings = async () => {
    try {
      setLoading(true);
      const res = await api.get('/api/services/my-services');
      setListings(res.data);
    } catch (err) {
      console.error('Failed to load listings:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMyListings();
  }, []);

  const openCreateModal = () => {
    setEditItem(null);
    setUploadedImageUrl('');
    setBriefInput('');
    reset({
      title: '',
      description: '',
      category: 'Technical',
      price: '',
      delivery_time: '',
      tags: '',
      status: 'available'
    });
    setShowModal(true);
  };

  const openEditModal = (service) => {
    setEditItem(service);
    setUploadedImageUrl(service.image_url || '');
    setBriefInput('');
    reset({
      title: service.title,
      description: service.description,
      category: service.category,
      price: service.price,
      delivery_time: service.delivery_time,
      tags: service.tags || '',
      status: service.status
    });
    setShowModal(true);
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this listing?')) return;
    
    setMsg({ text: '', type: '' });
    try {
      await api.delete(`/api/services/${id}`);
      setMsg({ text: 'Listing deleted successfully.', type: 'success' });
      fetchMyListings();
    } catch (err) {
      setMsg({ text: 'Failed to delete listing.', type: 'error' });
    }
  };

  const handleImageUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);
    setUploadingImage(true);

    try {
      const res = await api.post('/api/services/upload-image', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      setUploadedImageUrl(res.data.url);
      setMsg({ text: 'Cover image uploaded!', type: 'success' });
    } catch (err) {
      setMsg({ text: 'Failed to upload visual cover.', type: 'error' });
    } finally {
      setUploadingImage(false);
    }
  };

  const handleGenerateAiDescription = async () => {
    if (!briefInput.trim()) {
      alert('Please enter a brief sentence about your service.');
      return;
    }

    setGeneratingAi(true);
    try {
      const res = await api.post('/api/services/generate-description', {
        brief: briefInput.trim()
      });
      setValue('description', res.data.generated_description);
      setMsg({ text: 'Description generated by Gemini AI!', type: 'success' });
    } catch (err) {
      console.error(err);
      setMsg({ text: 'Gemini AI description builder failed. Try typing manually.', type: 'error' });
    } finally {
      setGeneratingAi(false);
    }
  };

  const onSubmit = async (data) => {
    setMsg({ text: '', type: '' });
    setSubmitting(true);
    
    const payload = {
      title: data.title,
      description: data.description,
      category: data.category,
      price: parseFloat(data.price),
      delivery_time: parseInt(data.delivery_time),
      image_url: uploadedImageUrl,
      tags: data.tags,
      status: data.status
    };

    try {
      if (editItem) {
        await api.put(`/api/services/${editItem.id}`, payload);
        setMsg({ text: 'Listing updated successfully!', type: 'success' });
      } else {
        await api.post('/api/services', payload);
        setMsg({ text: 'Listing created successfully!', type: 'success' });
      }
      
      setTimeout(() => {
        setShowModal(false);
        fetchMyListings();
      }, 1000);
      
    } catch (err) {
      const errorText = err.response?.data?.detail || 'Failed to submit service listing form.';
      setMsg({ text: errorText, type: 'error' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="py-6 space-y-6 max-w-7xl mx-auto px-4">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-sans text-2xl font-extrabold tracking-tight text-gray-900 dark:text-white sm:text-3xl">
            My Service Listings
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Publish and manage student services you offer to peers on campus.
          </p>
        </div>
        <div>
          <button
            onClick={openCreateModal}
            className="inline-flex items-center space-x-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-brand-500 dark:bg-brand-700 dark:hover:bg-brand-600"
          >
            <Plus className="h-5 w-5" />
            <span>Create Listing</span>
          </button>
        </div>
      </div>

      {msg.text && (
        <div className={`flex items-center space-x-2 rounded-lg p-4 text-sm ${
          msg.type === 'success' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-400' : 'bg-red-50 text-red-700 dark:bg-red-950/20 dark:text-red-400'
        }`}>
          {msg.type === 'success' ? <CheckCircle2 className="h-5 w-5" /> : <AlertCircle className="h-5 w-5" />}
          <span>{msg.text}</span>
        </div>
      )}

      {loading ? (
        <LoadingSpinner />
      ) : listings.length === 0 ? (
        <div className="rounded-xl border border-dashed border-gray-200 p-12 text-center text-sm text-gray-500 dark:border-darkBorder dark:text-gray-400 bg-white dark:bg-darkCard">
          You have not created any listings yet. Offer your skills and get paid by campus peers!
        </div>
      ) : (
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {listings.map((item) => (
            <div
              key={item.id}
              className="flex flex-col justify-between overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm dark:border-darkBorder dark:bg-darkCard p-4"
            >
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-brand-50 text-brand-700 dark:bg-brand-950/20 dark:text-brand-400 border border-brand-200/40">
                    {item.category}
                  </span>
                  <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded ${
                    item.status === 'available' ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'
                  }`}>
                    {item.status}
                  </span>
                </div>
                
                <h3 className="text-sm font-bold text-gray-900 dark:text-white line-clamp-1">{item.title}</h3>
                <p className="text-xs text-gray-500 dark:text-gray-400 line-clamp-2">{item.description}</p>
                
                <div className="flex items-center gap-4 text-xs text-gray-400">
                  <span className="flex items-center"><Clock className="h-3.5 w-3.5 mr-1" /> {item.delivery_time} days</span>
                  <span className="font-bold text-brand-600 dark:text-brand-400">₹{item.price}</span>
                </div>
              </div>
              
              <div className="mt-4 border-t border-gray-50 pt-3 flex items-center justify-end gap-2 dark:border-darkBorder">
                <button
                  onClick={() => openEditModal(item)}
                  className="rounded-lg p-2 text-gray-500 hover:bg-gray-50 dark:text-gray-400 dark:hover:bg-darkBg"
                  title="Edit Listing"
                >
                  <Edit className="h-4.5 w-4.5" />
                </button>
                <button
                  onClick={() => handleDelete(item.id)}
                  className="rounded-lg p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20"
                  title="Delete Listing"
                >
                  <Trash2 className="h-4.5 w-4.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create / Edit Modal overlay */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/40 backdrop-blur-sm overflow-y-auto">
          <div className="w-full max-w-2xl bg-white rounded-2xl border border-gray-100 p-6 shadow-xl dark:bg-darkCard dark:border-darkBorder max-h-[90vh] overflow-y-auto space-y-6">
            
            <div className="flex justify-between items-center border-b border-gray-50 pb-3 dark:border-darkBorder">
              <h3 className="text-lg font-bold text-gray-900 dark:text-white">
                {editItem ? 'Edit Service Listing' : 'Publish New Service'}
              </h3>
              <button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-gray-900">
                &times;
              </button>
            </div>

            {/* AI Generator Helper container */}
            <div className="rounded-xl border border-brand-200 bg-brand-50/50 p-4 dark:border-brand-950/20 dark:bg-brand-950/10 space-y-3">
              <div className="flex items-center space-x-1.5 text-xs text-brand-700 dark:text-brand-400 font-bold uppercase tracking-wider">
                <Sparkles className="h-4 w-4" />
                <span>AI Service Description Writer</span>
              </div>
              <p className="text-[10px] text-gray-500">Provide a short brief and let Gemini build a structured details package automatically!</p>
              
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="e.g. I teach Python, OOP coding lab assignments and debug issues."
                  value={briefInput}
                  onChange={(e) => setBriefInput(e.target.value)}
                  className="flex-1 rounded-xl border border-gray-200 bg-white py-2 px-3 text-xs focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                />
                <button
                  type="button"
                  onClick={handleGenerateAiDescription}
                  disabled={generatingAi}
                  className="rounded-xl bg-brand-600 px-4 py-2 text-xs font-bold text-white shadow hover:bg-brand-500 disabled:opacity-75"
                >
                  {generatingAi ? 'Writing...' : 'Build Draft'}
                </button>
              </div>
            </div>

            <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
              
              {/* Title */}
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase">Service Title</label>
                <input
                  type="text"
                  placeholder="e.g. Technical Tutoring in Python & DSA Lab Tasks"
                  {...register('title', { required: 'Title is required', minLength: { value: 5, message: 'Too short' } })}
                  className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                />
                {errors.title && <p className="mt-1 text-xs text-red-600">{errors.title.message}</p>}
              </div>

              {/* Category */}
              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase">Category</label>
                  <select
                    {...register('category')}
                    className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                  >
                    <option value="Technical">Technical</option>
                    <option value="Academic">Academic</option>
                    <option value="Creative">Creative</option>
                    <option value="Career">Career</option>
                    <option value="Other">Other</option>
                  </select>
                </div>

                {/* Status */}
                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase">Listing Availability</label>
                  <select
                    {...register('status')}
                    className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                  >
                    <option value="available">Available (Accepting Orders)</option>
                    <option value="busy">Busy (Temporarily Unavailable)</option>
                    <option value="offline">Offline</option>
                  </select>
                </div>
              </div>

              {/* Price and Delivery Duration */}
              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase">Price Rate (₹)</label>
                  <input
                    type="number"
                    placeholder="500"
                    {...register('price', { required: 'Price rate is required', min: { value: 1, message: 'Must be positive' } })}
                    className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                  />
                  {errors.price && <p className="mt-1 text-xs text-red-600">{errors.price.message}</p>}
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase">Delivery Time (Days)</label>
                  <input
                    type="number"
                    placeholder="2"
                    {...register('delivery_time', { required: 'Delivery time is required', min: { value: 1, message: 'Must be positive' } })}
                    className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                  />
                  {errors.delivery_time && <p className="mt-1 text-xs text-red-600">{errors.delivery_time.message}</p>}
                </div>
              </div>

              {/* Tags */}
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase">Search Tags (Comma-Separated)</label>
                <input
                  type="text"
                  placeholder="python, coding, guidance, homework"
                  {...register('tags')}
                  className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white"
                />
                <p className="text-[10px] text-gray-400 mt-1">Separate keywords using commas</p>
              </div>

              {/* Image Upload */}
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase">Service Cover Visual (Optional)</label>
                <div className="mt-2 flex items-center space-x-4">
                  {uploadedImageUrl ? (
                    <img
                      src={uploadedImageUrl.startsWith('http') ? uploadedImageUrl : `${API_BASE_URL}${uploadedImageUrl}`}
                      alt="Service Visual"
                      className="h-14 w-24 object-cover rounded border border-gray-100 dark:border-darkBorder"
                    />
                  ) : (
                    <div className="flex h-14 w-24 items-center justify-center rounded border border-dashed border-gray-200 bg-gray-50 text-gray-400 text-xs dark:bg-darkBg dark:border-darkBorder">
                      No visual
                    </div>
                  )}

                  <label className="inline-flex items-center space-x-1 rounded border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-gray-700 cursor-pointer hover:bg-gray-50 dark:border-darkBorder dark:bg-darkBg dark:text-gray-300">
                    <Upload className="h-3.5 w-3.5" />
                    <span>{uploadingImage ? 'Uploading...' : 'Choose File'}</span>
                    <input type="file" onChange={handleImageUpload} className="hidden" accept="image/*" />
                  </label>
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase">Detailed Description</label>
                <textarea
                  rows={6}
                  placeholder="Draft your course details, delivery materials, scope of instructions, and prerequisites..."
                  {...register('description', { required: 'Detailed overview is required', minLength: { value: 20, message: 'Too short' } })}
                  className="mt-1 block w-full rounded-xl border border-gray-200 bg-gray-50/50 py-2.5 px-3 text-sm focus:outline-none dark:border-darkBorder dark:bg-darkBg dark:text-white font-mono text-xs"
                />
                {errors.description && <p className="mt-1 text-xs text-red-600">{errors.description.message}</p>}
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-gray-50 dark:border-darkBorder">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="rounded-xl bg-brand-600 px-6 py-2.5 text-xs font-bold text-white shadow-md hover:bg-brand-500 disabled:opacity-75"
                >
                  {submitting ? 'Saving...' : 'Publish Listing'}
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

    </div>
  );
};

export default MyServices;
